// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/nmsn/Studio/utils/node_modules/.pnpm/dumi@2.1.3_p43kv7syaqeenukg3wufpdkb6e/node_modules/dumi/theme-default/builtins/Container/index.js';
