name: codecov

on:
  push:
   branches:
    - main

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:

    - name: "Set node"
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: "Install"
      run: npm ci

    - name: "Run test"
      run: npm test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
